### ISSUE TITLE
Zacian-Crowned Moveset Incorrect

### ISSUE THREAD

**Issue by sdeiley** [GregLyons/poke-team#1]
In `Builder->Team`, if you select Zacian-Crowned, the only learned moves shown are 
- Behemoth Blade,
- Max Guard, and 
- Max Steelspike, 
the last two of which aren’t possible.  

There’s probably some copying w/ DB data needed to ensure that Zacian-Crowned is applied all moves from Zacian.  I didn’t verify with other mons that may have these kinds of edge cases, such as Zamazenta, Giratina, Kyruem, Calyrex-Shadow, etc.
![AF17E101-619A-44B5-A840-961159BEA735](https://user-images.githubusercontent.com/6296262/162643576-0332964b-75cc-4aee-b105-87c5f4662a3d.png)

**Comment by GregLyons** [comment]
Your suspicion is correct. The underlying database starts from the Smogon learnset data [here](https://github.com/smogon/pokemon-showdown/blob/master/data/learnsets.ts) and merges together some learnsets (Gen 2 and BD/SP) from the `mods` there to get a complete dataset. Some of the Pokemon in that set have "missing" learnsets (e.g. `deoxysspeed`), presumably because Pokemon Showdown has some other algorithm for adding the learnset data for Deoxys Speed.

What happened was this: I was aware of this issue, so I checked for Pokemon whose learnsets in the PS data were empty, and in that case I would add the learnsets (e.g. `deoxys` to `deoxysspeed`) when appropriate. What I didn't anticipate, however, was the case in which a Pokemon form gains a new move, like Zacian Crowned gaining Behemoth Blade. In the PS data, you'll see that the entry for `zaciancrowned` just has Behemoth Blade. So my check missed these cases, since it was checking for *empty* learnsets. The Rotom forms were also affected by this, as were some others.

For some reason, Calyrex Shadow *does* have full learnset data in the PS dataset, even though he gains a signature move but otherwise shares moves with Calyrex. Maybe because he also shares moves with Glastrier? I checked for learnset move counts below a certain threshold (10) and excluded obvious cases like Ditto (this is what flagged Rotom forms), so this should be fixed now.  Here are some screenshots from the site now with there moves filled in:

![zacian_moves](https://user-images.githubusercontent.com/89315619/162748747-c88a30b4-d086-492b-a454-2be3bb0e54ed.png)
![rotom_moves](https://user-images.githubusercontent.com/89315619/162748765-505a0161-1507-4eb4-8bd0-70990b90cfaf.png)

Given Zacian's prominence in AG, as several other Pokemon being affected, I figured it's best to update this now instead of waiting to batch it with other data errors.

Thanks for finding the bug!

**Comment by sdeiley** [comment]
Actually the Eternatus max moves are not usable in game, they're only programmed in for a boss battle :) definitely makes sense you didn't know this w/o playing the game tho!
________________________________

**Comment by GregLyons** [comment]
Hahaha this is why I need users who play/keep up with the games and PS regularly to weigh in 😉

I'm testing the website now and it looks like Both Zacian/Zamazenta forms, as well as Eternatus, have had their max moves removed (example with Zacian Crowned below).

![no_max](https://user-images.githubusercontent.com/89315619/162986192-08628164-3502-4888-a598-e9541761b3ae.png)

I think now it's safe to close this issue.

As for the VGC suggestion, I moved any potential discussion for that that to a Discussion thread (#2 ), as I just learned about that GitHub feature. I do believe both the points you bring up about VGC are good ones. Currently I think that's a bit too complicated for me to implement/maintain at this time, but I gave my thoughts on why/how one *could* go about implementing it in that thread.
